"""Add specialization and availability to User model

Revision ID: 6b99b86aad82
Revises: 80cd86d0b670
Create Date: 2025-10-18 11:51:13.143628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b99b86aad82'
down_revision = '80cd86d0b670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
