"""Add Medication model

Revision ID: cb639870fa56
Revises: 
Create Date: 2025-10-17 22:12:01.423681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb639870fa56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ehr', schema=None) as batch_op:
        batch_op.drop_column('medications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ehr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medications', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
